INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (1, N'Tách riêng 2 lòng đỏ trứng gà ra 1 âu lớn, cho vani, bột bắp đã chuẩn bị vào, khuấy đều.
Tiếp theo, thêm đường và sữa tươi vào âu hỗn hợp trứng, tiếp túc khuấy đến khi đường tan.
Bắc nồi lên bếp, đổ hỗn hợp bột bánh vào nồi đun trên lửa vừa, vừa đun vừa khuấy liên tục để hỗn hợp sệt lại và nổi bóng lên là được.
Phết một lớp dầu ăn vào trong hộp, sau đó đổ hỗn hợp bột vào, dùng tay ấn đều để hỗn hợp phẳng bề mặt. Đặt bột bánh vào trong ngăn mát tủ lạnh 90 phút.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Flam-bot-banh-sua-tuoi.webpdbeb7e8e-085a-419d-a244-810ad4602374?alt=media&token=30b1497f-ab6e-4fe8-b0a9-1fa9ef694c59', N'Làm bột bánh sữa tươi', N'', 1);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (2, N'Cho bột chiên xù vào máy xay sinh tố, xay nhuyễn
Lưu ý: Trong trường hợp không có máy xay bạn có thể làm nhuyễn bột chiên xù bằng cách giã bằng cối và chày.', N'https://www.google.com/url?sa=i&url=https%3A%2F%2Fblog.beemart.vn%2Fcach-lam-bot-chien-xu-tu-vun-banh-mi-don-gian-tai-nha%2F&psig=AOvVaw0uIig5SHGFGHRnWQAxopkq&ust=1667640123732000&source=images&cd=vfe&ved=0CA0QjRxqFwoTCLjSo9uZlPsCFQAAAAAdAAAAABAU', N'Xay nhỏ bột chiên', N'', 1);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (3, N'Tách riêng lòng đỏ và lòng trắng của 4 quả trứng gà ra 2 âu. 
Đập quả trứng gà cuối cùng vào âu lòng đỏ, khuấy đều. Khi thấy trứng nổi bong bóng thì dừng lại.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fdanh-trung-ga.webpfffb8e75-74da-456b-b4c8-e8c4766103d2?alt=media&token=af566852-39a4-4896-b641-84502ab6f6e8', N'Đánh trứng gà', N'', 1);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (4, N'Hết 90 phút, lấy bột bánh trong tủ lạnh ra, cắt thành các miếng hình chữ nhật vừa ăn. Bạn cũng có thể tạo hình cho bánh tùy theo sở thích và sự sáng tạo của mình.
Lần lượt cho từng miếng bánh vào âu trứng, lật qua lật lại để trứng bám đều các mặt rồi lăn qua bột chiên xù đã xay mịn.
Lặp lại thao tác lăn bánh qua trứng và bột thêm một lần nữa.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fchien-banh-sua-tuoi.webp2d6a04d6-27c6-4abd-be6c-f6280e96180e?alt=media&token=6052bd67-d3bd-4918-a2d6-3d37da41cf77', N'Chuẩn bị bánh để chiên', N'', 1);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (5, N'Đun nóng dầu ăn trong chảo, thả từng miếng bánh vào chiên trên lửa to. Lưu ý: Trở bánh liên tục để bánh chín đều.
Khi thấy bánh đã chín vàng thì vớt bánh ra dĩa. Tiếp tục chiên hết phần bánh đã chuẩn bị.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fbanh-sua-tuoi-chien-gion.webp6c7eb0b9-2daa-4055-8d78-8d6aada8110a?alt=media&token=4a9d7206-def9-4a73-940b-9c33470770a7', N'Chiên bánh', N'', 1);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (9, N'Sau khi cho bột vào túi bắt bông kem, bạn lót một tấm giấy chống dính (giấy nến) lên vỉ nướng, bóp nhẹ túi để tạo hình bột thành những chiếc bông xinh xắn.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fbuoc3.jpgc2f38c2b-fcfb-454a-9036-310c944135d7?alt=media&token=802a3afc-57c9-4142-b3cd-dea5f27e7741', N'Tạo hình bánh', N'', 18);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (10, N'Sau đó, bạn bỏ bột vào nồi chiên không dầu, nướng ở 160 độ C trong 15 phút. Nướng tiếp 5 phút với 80 độ C cho bánh giòn hơn.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fbuoc5.jpg20728f95-453d-4032-9532-7a30eecb74a0?alt=media&token=d11c5493-0fd4-40ac-b1d3-716f0db8a3d3', N'Nướng bánh', N'', 18);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (11, N'Bạn rửa sạch 250gr đậu xanh rồi cho vào ngâm cùng nước nóng khoảng 2 - 3 giờ. Nếu sử dụng nước lạnh thì cho đậu ngâm qua đêm.
Đậu sau khi ngâm, bạn tiến hành đãi sạch vỏ còn sót lại rồi cho vào nồi nấu chín.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fbuwoc1banhtrungthu.jpgf1971182-9928-4cb5-b2d5-026d3844b940?alt=media&token=83b140c3-70fc-4660-8597-3fdff41724a8', N'Ngâm và nấu đậu xanh', N'', 19);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (12, N'Bạn cho phần đậu xanh đã được nấu chín cùng 200gr đường cát vào máy xay sinh tố và xay nhuyễn hỗn hợp, rồi rây cho mịn.
Sau đó, bạn cho hỗn hợp ra chảo chống dính, tiến hành sên cho đến khi thấy hỗn hợp sệt lại.
Khi thấy phần hỗn hợp đậu bắt đầu sệt lại, bạn cho từ từ 100gr dầu ăn vào và đảo liên tục cho đến khi sờ vào phần hỗn hợp không còn bị dính tay là được.
Tiếp tục, bạn cho thêm 20gr bột bánh dẻo vào chảo và trộn đều là xong. Đợi đến khi hỗn hợp đậu xanh nguội thì cho ra khay rồi vò thành từng viên tròn dựa trên trọng lượng của bánh.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fbuoc2banhtrungthu.jpg9dbe375e-9ce2-4bbb-a56c-63318c43aa8d?alt=media&token=2eda598e-ee55-4703-8a9d-a71557d08ef7', N'Sên nhân đậu xanh', N'', 19);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (13, N'Bạn cho tất cả các nguyên liệu gồm 250gr nước đường bánh nướng, 30gr đậu phộng, 15gr bột sư tử, 40gr mạch nha, 1 lòng đỏ trứng gà và 50gr dầu ăn vào tô, trộn đều và ủ trong 30 phút.
Sau đó, bạn cho thêm 320gr bột mì vào tô qua rây lọc, rồi trộn thật nhanh và đều tay để hỗn hợp thành khối bột mịn. Nếu cảm thấy ướt thì cho thêm bột mì vào.
Khi khối bột đã mịn thì bạn ủ tiếp 30 phút - 1 giờ cho bột nghỉ rồi mới tiến hành đóng bánh.
Bạn nhớ bật lò nướng ở 220 độ C trong 15 phút trước khi nướng bánh để làm nóng lò.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fb3banhtrungthu.jpg031efda6-bff2-443b-bd54-7650431ccb9e?alt=media&token=a0ac7420-ae36-48e7-9623-0e70d3aae31c', N'Trộn vỏ bánh', N'', 19);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (14, N'Bạn cho phần bánh đã vo vào khuôn đóng. Bạn đóng bánh 2 lần, lần đầu nhấn tay thật chặt, lần thứ hai nhấn thêm rồi từ từ thả bánh vào khay đã được lót 2 lớp giấy bạc và 3 lớp giấy nướng.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fb4dongbanh.jpgb9bbec0a-fdd7-4e44-8c8c-eed9ad55e0f9?alt=media&token=d27e5354-3dc9-465e-9cda-b0e84a7a7822', N'Đóng bánh', N'', 19);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (15, N'Bạn đánh đều hỗn hợp gồm 1/4 lòng trắng trứng gà, 1 lòng đỏ trứng gà, 1 muỗng cà phê sữa tươi, 1 muỗng cà phê dầu mè, 3 giọt rượu mai quế lộ (khoảng 5ml), rồi lọc 3 lần hỗn hợp qua rây. Sau đó, bạn phết hỗn hợp lên trên mặt bánh.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fb5nuongbanh.jpg7befdb36-6ee4-4e43-ac1a-9a081e6ac788?alt=media&token=5f27619e-32ea-4ced-b4ef-d6b5934d2ebd', N'Nướng bánh', N'', 19);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (16, N'Vo sạch 240gr đậu xanh, sau đó ngâm từ 4 - 6 tiếng cho mềm.
Chắt bỏ phần nước ngâm, cho đậu xanh vào nồi cùng 1/2 muỗng cà phê muối, 800ml nước. Nấu đậu trên lửa vừa trong vòng 15 phút.
Sau đó, bạn cho vào thêm 240gr đường, khuấy đều rồi đậy nắp nấu đậu thêm 5 phút nữa cho gần cạn nước.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fb1ngamdau.jpg4040533a-0c2d-41a1-a990-6895131571f7?alt=media&token=21198d71-4873-41a3-baf7-c74118dd5277', N'Ngâm và nấu đậu xay', N'', 20);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (17, N'Cho phần đậu xanh đã nấu chín vào máy xay sinh tố rồi xay nhuyễn mịn.
Bắc chảo lên bếp, cho vào đậu xanh đã xay vào rồi khuấy đều trên lửa nhỏ. Tiếp theo, cho từ từ 4 muỗng canh dầu ăn vào chảo (mỗi lần cho 2 muỗng), rồi khuấy đều để hỗn hợp hòa quyện.
Hòa tan 1.5 muỗng canh bột mì cùng 3 muỗng canh nước lọc. Cho từ từ hỗn hợp bột vào chảo rồi tiếp tục sên đến khi nhân tạo thành khối dẻo mịn, không dính chảo và không bị chảy xệ là được.
Cuối cùng, cho nhân ra tô và để nguội.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fbuoc2banhtrungthu.jpg0b0af2b1-3fb7-43f7-b911-afb56b7e19c7?alt=media&token=4bbdaa3a-3f39-4860-b80c-8b6840755528', N'Sên nhân đậu xanh', N'', 20);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (18, N'Cho vào tô 7 quả trứng muối, 1 ít rượu trắng rồi đảo đều.
Tiếp theo, xếp trứng lên khay có lót sẵn 1 tấm giấy nến, phết 1 lớp dầu mè lên trứng rồi nướng 5 phút ở 170 độ C.
Sau khi nướng chín, bạn để yên trứng trong nồi chiên không dầu thêm 5 phút nữa rồi mới lấy ra.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Ftrungmuoi.jpg8c333bc5-2212-4576-8ec0-90c43a190b45?alt=media&token=5cfc3534-a10d-4a42-b157-8453e1314727', N'Sơ chế và nướng trứng muối', N'', 20);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (19, N'Chia vỏ bánh và nhân theo tỉ lệ 66gr vỏ bánh : 135gr nhân bánh (đã bao gồm trứng muối) và vo tròn.
Dùng ngón cái ấn vào giữa viên đậu xanh, sau đó bạn cho 1 quả trứng muối vào rồi túm kín nhân lại.
Tiếp theo, dùng cây cán mỏng bột vỏ bánh, cho nhân vào giữa rồi túm kín lại, vo tròn.
Áo khuôn với 1 lớp dầu ăn, cho bánh vào trong rồi dùng tay ấn mạnh để bánh dàn đều khuôn. Sau đó, ấn mạnh phần lò xo, giữ yên trong 10 giây để tạo hình cho bánh.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fb4dongbanh.jpgec7e86a4-56db-4215-bbda-61898bafe9b0?alt=media&token=406fb54c-6e52-49fa-888e-761095b7637d', N'Đóng bánh', N'', 20);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (20, N'Làm nóng nồi chiên không dầu trước ở 200 độ C trong 15 phút.
Xếp bánh lên khay có lót sẵn giấy nến, sau đó xịt phun sương nước lên mặt bánh. Nướng lần 1 ở 145 độ C trong 5 phút. Sau 5 phút, lấy bánh ra để nguội hẳn.
Khuấy tan 1 lòng đỏ trứng gà cùng 1 muỗng canh sữa tươi không đường. Phết lớp mỏng hỗn hợp trứng lên mặt bánh đã để nguội và nướng lần 2 ở 145 độ C từ 5 - 7 phút.
Sau lần nướng thứ 2, bạn trở mặt bánh lại và nướng lần 3 thêm 5 phút nữa ở 145 độ C là hoàn tất.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fnuongbanh.jpgd59d60e5-14bf-4004-9339-b26e02c0fd4c?alt=media&token=7c762906-5a57-4bd4-9a7d-497c9f289f4a', N'Nướng bánh', N'', 20);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (21, N'Bạn dùng một cái tô lớn cho bột mì và bột gạo vào trộn đều. Rót từ từ nước lọc vào tô bột, vừa rót vừa khuấy đều cho đến khi có hỗn hợp bột sền sệt là được.
Tiếp theo bạn cho vào hỗn hợp bột 1/2 muỗng cà phê muối, 1 muỗng canh đường, 2 ống vani khuấy đều. Sau đó bạn để vào chỗ thoáng để bột nghỉ 30 phút. Trong thời gian chờ đợi bạn tiến hành sơ chế chuối.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fpha-bot.jpga82e5839-4737-4c37-96f7-efb54b4f6bcd?alt=media&token=ae185831-adbf-4020-8be0-999069c13e10', N'pha bột', N'', 21);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (22, N'Chuối sứ bạn bóc vỏ, quả lớn cắt làm 2, quả nhỏ để nguyên, sau đó cho chuối vào bọc ni lông sạch, dùng dao hoặc cây lăn bột ép nhẹ cho chuối hơi bẹp ra. Bạn không ép mạnh tay làm chuối bị nát không chiên được.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fso-che-chuoi.jpgba4dc5ee-a367-46ad-b195-52bcfec31a33?alt=media&token=db63eba0-a5ee-4613-8e2f-c978d31f204a', N'Sơ chế chuối', N'', 21);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (23, N'Bạn đặt chảo dầu sâu lòng lên bếp, làm nóng chảo sau đó cho dầu ăn và chảo sao cho khi chiên dầu ngập miếng chuối.
Đun nóng dầu ăn sau đó gắp miếng chuối nhúng vào bột sao cho bột phủ đều bên ngoài miếng chuối. Bạn gắp miếng chuối nhấc lên cao, đợi một chút để bột thừa rớt lại vào tô rồi mới bỏ vào chảo chiên.
Chiên bánh với lửa nhỏ đến khi thấy bánh chuyển màu vàng, bạn vớt bánh ra để vào đĩa có lót giấy thấm dầu, bánh được thấm bớt lượng dầu dư sẽ giòn lâu hơn và ăn đỡ ngán hơn.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fchien-banh.jpg12492fd9-f7ab-4c04-843f-0f515c07925e?alt=media&token=cd08a199-31d5-40ed-bc78-16e14d70c719', N'Chiên bánh', N'', 21);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (25, N'Khi hỗn hợp bơ của bạn đã bông lên và có màu vàng kem, bạn rây 145g bột mì vào. Nhớ là phải rây để bột không bị vón cục nha.
Bạn trộn đều cho bột hòa quyện vào bơ. Khi bột đã hòa quyện lại hết, bạn cho bột vào một túi bắt bông kem.
', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fdownload%20(1).jfif1f7785be-d552-49ed-a3c0-c7605386ce18?alt=media&token=5dd6f50b-fbc0-4b10-b2ba-3fbf48fd5b09', N'Trộn bột', N'', 28);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (26, N'Sau khi cho bột vào túi bắt bông kem, bạn lót một tấm giấy chống dính (giấy nến) lên vỉ nướng, bóp nhẹ túi để tạo hình bột thành những chiếc bông xinh xắn.
', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fdownload%20(2).jfifaa69c138-c657-461a-bff0-6f1a1532858d?alt=media&token=bb190ee2-aab4-4eea-80a2-cf888e8549fe', N'Tạo hình bánh', N'', 28);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (34, N'Sau đó, bạn bỏ bột vào nồi chiên không dầu, nướng ở 160 độ C trong 15 phút. Nướng tiếp 5 phút với 80 độ C cho bánh giòn hơn.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fbuoc3.jpg4a30bfb8-3af9-4d07-8ce9-d698b58f15aa?alt=media&token=83bd32f5-3836-4b8a-94d9-63a4e103ea63', N'Nướng bánh', N'', 41);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (37, N'Khi hỗn hợp bơ của bạn đã bông lên và có màu vàng kem, bạn rây 145g bột mì vào. Nhớ là phải rây để bột không bị vón cục nha.
Bạn trộn đều cho bột hòa quyện vào bơ. Khi bột đã hòa quyện lại hết, bạn cho bột vào một túi bắt bông kem.
', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fbuoc2.jpg5555d54e-b298-4180-b0df-7ec6bbae675f?alt=media&token=56360a2d-53bc-4909-bd79-d1f28be9532d', N'Trộn bột', N'', 53);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (38, N'Sau đó, bạn bỏ bột vào nồi chiên không dầu, nướng ở 160 độ C trong 15 phút. Nướng tiếp 5 phút với 80 độ C cho bánh giòn hơn.', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fbuoc5.jpg255d3b7d-2ab2-452c-8d67-59c8d8698443?alt=media&token=f68622b0-7962-46a4-8a77-1421b3037dda', N'Nướng bánh', N'', 53);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (39, N'Đầu tiên, bạn lấy 80g bơ lạt cho vào một cái tô lớn. Nếu bạn để bơ trong tủ lạnh, bạn hãy lấy bơ ra khỏi tủ lạnh, để ở nhiệt độ phòng trong 10 phút.
Kế đến, bạn dùng cây đánh trứng, đánh đều bơ trong khoảng 1 phút. Bạn chia đường ra làm 3 phần, cho lần lượt từng phần vào bơ, tiếp tục đánh cho đều tay.
Nếu có máy đánh trứng, bạn có thể dùng để đánh hỗn hợp cho nhanh. Bạn đánh bơ với đường quyện vào nhau cho đến khi nào thấy đường tan hết và bơ chuyển sang màu vàng kem, cho tiếp 1 quả trứng vào hỗn hợp, đánh cho thật bông lên.
Kế đến, bạn cho tiếp 1 ống vani, 10ml sữa tươi vào, tiếp tục đánh đều.
', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fbuoc3.jpg8fa4c954-d061-4285-9825-99682f1e3f38?alt=media&token=15fef0f0-aad3-4f08-b93d-a04fee76d00d', N'Đánh hỗn hợp bơ', N'', 59);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (40, N'Đầu tiên, bạn lấy 80g bơ lạt cho vào một cái tô lớn. Nếu bạn để bơ trong tủ lạnh, bạn hãy lấy bơ ra khỏi tủ lạnh, để ở nhiệt độ phòng trong 10 phút.
Kế đến, bạn dùng cây đánh trứng, đánh đều bơ trong khoảng 1 phút. Bạn chia đường ra làm 3 phần, cho lần lượt từng phần vào bơ, tiếp tục đánh cho đều tay.
Nếu có máy đánh trứng, bạn có thể dùng để đánh hỗn hợp cho nhanh. Bạn đánh bơ với đường quyện vào nhau cho đến khi nào thấy đường tan hết và bơ chuyển sang màu vàng kem, cho tiếp 1 quả trứng vào hỗn hợp, đánh cho thật bông lên.
Kế đến, bạn cho tiếp 1 ống vani, 10ml sữa tươi vào, tiếp tục đánh đều
', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fbuoc3.jpgd89af06f-ef41-41a4-97c1-a583c850d4ca?alt=media&token=1ad4c0b0-bb54-421e-a1ca-1ead824de4d9', N'bánh quy bơ Danisa', N'', 60);
INSERT INTO BakeryRecipe.dbo.step (step_id, description, image, name, video, post_id) VALUES (41, N'
Khi hỗn hợp bơ của bạn đã bông lên và có màu vàng kem, bạn rây 145g bột mì vào. Nhớ là phải rây để bột không bị vón cục nha.
Bạn trộn đều cho bột hòa quyện vào bơ. Khi bột đã hòa quyện lại hết, bạn cho bột vào một túi bắt bông kem.
', N'https://firebasestorage.googleapis.com/v0/b/bakery-9a92d.appspot.com/o/images%2Fbuoc2banhtrungthu.jpga87635a7-c589-46d3-86e2-4fc339d12993?alt=media&token=cd71b1b5-ed4b-4bd1-ab59-1326690b4235', N'Trộn bột', N'', 60);
